# docker-compose up -d

version: '3.2'
networks:
  steamfitter-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name:  steamfitter-postgres
    environment:
      POSTGRES_DB: steamfitter_api
      POSTGRES_USER: steamfitter
      POSTGRES_PASSWORD: Tartans@@1
    volumes:
      - ./_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steamfitter"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - steamfitter-network
    restart: always

  steamfitter-api:
    image: steamfitter/api
    container_name: steamfitter-api
    depends_on:
      - postgres
    ports:
      - "4400:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - steamfitter-network
    restart: always
