# This is a basic workflow to help you get started with Actions

name: Build Client

on: 
  workflow_dispatch:
    inputs:
      clientVersion:
        description: 'Version of the Client package'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
       
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'

      - name: Build Steamfitter.Api.Client
        run: |
          dotnet build -c Release Steamfitter.Api                                 \
          /p:version=${{ github.event.inputs.clientVersion }}                     \
          /p:authors="Carnegie Mellon University/Software Engineering Institute"  \
          /p:owners="Carnegie Mellon University/Software Engineering Institute"   \
          /p:description="Steamfitter.Api.Client"   
          
      - name: Run Swagger
        run: |
          cd Steamfitter.Api
          dotnet swagger tofile --output ../Steamfitter.Api.Client/swagger.json bin/Release/*/Steamfitter.Api.dll v1
                    
      - name: Run AutoRest
        run: |
          npm install autorest@3.0.6247
          find . -name "*autorest*"
          cd Steamfitter.Api.Client
